license_id: cc-by
methodology: "[ENSO FAQ](https://www.cpc.ncep.enso.gov/products/analysis_monitoring/ensostuff/ensofaq.shtml#ENSO)  \n
  [Description of Changes to Ocean Niño Index (ONI)](https://origin.cpc.ncep.enso.gov/products/analysis_monitoring/ensostuff/ONI_change.shtml)"
caveats: None
dataset_source: National Oceanic and Atmospheric Administration (enso) / Climate Prediction Center (CPC)
package_creator: HDX Data Systems Team
private: False
maintainer: b682f6f7-cd7e-4bd4-8aa7-f74138dc6313 # berylnyamgeroh
owner_org: hdx
data_update_frequency: 30 # first Thursday of each month
notes: "ENSO stands for El Niño/ Southern Oscillation. The ENSO cycle refers to the coherent and sometimes very strong year-to-year variations in sea- surface temperatures, convective rainfall, surface air pressure, and atmospheric circulation that occur across the equatorial Pacific Ocean. El Niño and La Niña represent opposite extremes in the ENSO cycle.  \n
  El Niño refers to the above-average sea-surface temperatures that periodically develop across the east-central equatorial Pacific. It represents the warm phase of the ENSO cycle, and is sometimes referred to as a Pacific warm episode.  \n
  La Niña refers to the periodic cooling of sea-surface temperatures across the east-central equatorial Pacific. It represents the cold phase of the ENSO cycle, and is sometimes referred to as a Pacific cold episode.  \n
  \n [View the raw data](https://origin.cpc.ncep.enso.gov/products/analysis_monitoring/ensostuff/detrend.nino34.ascii.txt)  \n
  [View the processed data](https://origin.cpc.ncep.enso.gov/products/analysis_monitoring/ensostuff/ONI_v5.php)  \n
  \n Dataset field definitions:  \n
  date: Year-month-date (first day of month)  \n
  TOTAL: ERSST.v5 (sea surface temperature) in the Niño 3.4 region  \n
  ClimAdjust: adjustment for changing 30-year base period  \n
  ANOM: Oceanic Niño Index (ONI)  \n
  ANOM_trimester: 3-month rolling mean of ANOM (MO corresponds to first month of trimester)  \n
  ANOM_trimester_round: ANOM_trimester rounded to one decimal place  \n
  phase_trimester: phase of trimester based on ANOM_trimester_round  \n
  phase_event: elnino or lanina event (requiring at least 5 consecutive trimesters of the phase)"
