base_url: "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/detrend.nino34.ascii.txt"
title: "El Niño-Southern Oscillation (ENSO): El Niño and La Niña Events"
description: Monthly analysis of the El Niño-Southern Oscillation (ENSO) cycle

tags:
  - climate hazards
  - climate-weather
  - el nino-el nina
